[package]
name = "myLottoNumber"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "*"
crossterm= "*"
colored="*"
chrono="*"
rusqlite = { version = "0.37", features = ["bundled"] }
itertools = "0.14.0"
